[phases.setup]
nixPkgs = ["python311", "uv"]

[phases.install]
cmds = [
  "uv sync --frozen --no-dev"
]

[start]
cmd = "uv run uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHON_VERSION = "3.11"
